main:
  bin: "C:\\Users\\user\\Desktop\\backupfriend-client\\src\\rdiff-backup.exe"
  ssh: "C:\\Users\\user\\Desktop\\backupfriend-client\\ssh.exe"
  # bin: "__package_path__\rdiff-backup.exe"
backups:
  - name: "test"
    source: "c:\\a"
    dest: "user@gnethomelinux.com::/tmp/a"
    port: "8022"
    key: "c:\\b\\id_rsa"
    every: "daily"
    # evrey: "sunday"
    time: "20:47"

  - name: "test2"
    source: "/home/guy/xchat2.bak"
    dest: "user@gnethomelinux.com::/backup-data/test"
    port: "8022"
    key: "/home/guy/.ssh/id_rsa_passwordless"
    every: "daily"
    # evrey: "sunday"
    time: "04:32"
